//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ceza
    {
        public int id { get; set; }
        public Nullable<int> uye { get; set; }
        public Nullable<int> hareket { get; set; }
        public Nullable<System.DateTime> baslangic { get; set; }
        public Nullable<System.DateTime> bitis { get; set; }
        public Nullable<decimal> para { get; set; }
    
        public virtual hareket hareket1 { get; set; }
        public virtual uye uye1 { get; set; }
    }
}
